//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Акт вып раб.
    /// </summary>
    // *** Start programmer edit section *** (АктВыпРаб CustomAttributes)

    // *** End programmer edit section *** (АктВыпРаб CustomAttributes)
    [AutoAltered()]
    [Caption("Акт выполнения работ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АктВыпРабE", new string[] {
            "ОбщСтоим as \'Общая стоимость\'"})]
    [AssociatedDetailViewAttribute("АктВыпРабE", "ТЧАкт", "ТЧАктE", true, "", "Табличная часть акта выполнения работ", true, new string[] {
            ""})]
    [View("АктВыпРабL", new string[] {
            "ОбщСтоим as \'Общая стоимость\'"})]
    public class АктВыпРаб : ICSSoft.STORMNET.DataObject
    {
        
        private float fОбщСтоим;
        
        private IIS.Novyjj1.DetailArrayOfТЧАкт fТЧАкт;
        
        // *** Start programmer edit section *** (АктВыпРаб CustomMembers)

        // *** End programmer edit section *** (АктВыпРаб CustomMembers)

        
        /// <summary>
        /// ОбщСтоим.
        /// </summary>
        // *** Start programmer edit section *** (АктВыпРаб.ОбщСтоим CustomAttributes)

        // *** End programmer edit section *** (АктВыпРаб.ОбщСтоим CustomAttributes)
        public virtual float ОбщСтоим
        {
            get
            {
                // *** Start programmer edit section *** (АктВыпРаб.ОбщСтоим Get start)

                // *** End programmer edit section *** (АктВыпРаб.ОбщСтоим Get start)
                float result = this.fОбщСтоим;
                // *** Start programmer edit section *** (АктВыпРаб.ОбщСтоим Get end)

                // *** End programmer edit section *** (АктВыпРаб.ОбщСтоим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктВыпРаб.ОбщСтоим Set start)

                // *** End programmer edit section *** (АктВыпРаб.ОбщСтоим Set start)
                this.fОбщСтоим = value;
                // *** Start programmer edit section *** (АктВыпРаб.ОбщСтоим Set end)

                // *** End programmer edit section *** (АктВыпРаб.ОбщСтоим Set end)
            }
        }
        
        /// <summary>
        /// Акт вып раб.
        /// </summary>
        // *** Start programmer edit section *** (АктВыпРаб.ТЧАкт CustomAttributes)

        // *** End programmer edit section *** (АктВыпРаб.ТЧАкт CustomAttributes)
        public virtual IIS.Novyjj1.DetailArrayOfТЧАкт ТЧАкт
        {
            get
            {
                // *** Start programmer edit section *** (АктВыпРаб.ТЧАкт Get start)

                // *** End programmer edit section *** (АктВыпРаб.ТЧАкт Get start)
                if ((this.fТЧАкт == null))
                {
                    this.fТЧАкт = new IIS.Novyjj1.DetailArrayOfТЧАкт(this);
                }
                IIS.Novyjj1.DetailArrayOfТЧАкт result = this.fТЧАкт;
                // *** Start programmer edit section *** (АктВыпРаб.ТЧАкт Get end)

                // *** End programmer edit section *** (АктВыпРаб.ТЧАкт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктВыпРаб.ТЧАкт Set start)

                // *** End programmer edit section *** (АктВыпРаб.ТЧАкт Set start)
                this.fТЧАкт = value;
                // *** Start programmer edit section *** (АктВыпРаб.ТЧАкт Set end)

                // *** End programmer edit section *** (АктВыпРаб.ТЧАкт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АктВыпРабE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АктВыпРабE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АктВыпРабE", typeof(IIS.Novyjj1.АктВыпРаб));
                }
            }
            
            /// <summary>
            /// "АктВыпРабL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АктВыпРабL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АктВыпРабL", typeof(IIS.Novyjj1.АктВыпРаб));
                }
            }
        }
    }
}
