//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Бюд строи.
    /// </summary>
    // *** Start programmer edit section *** (БюдСтрои CustomAttributes)

    // *** End programmer edit section *** (БюдСтрои CustomAttributes)
    [AutoAltered()]
    [Caption("Бюджет строительства")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БюдСтроиE", new string[] {
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.НаимРабот as \'Номенклатура\'",
            "ЕдИзмер as \'Единицы измерения\'",
            "ЕдИзмер.Наименование as \'Единицы измерения\'",
            "Объем as \'Объем\'",
            "НачРаб as \'Начала работ\'",
            "ОкоРаб as \'Окончания работ\'",
            "Длите as \'Длительность\'",
            "БазСт as \'Базовая стоимость\'",
            "СтоимИто as \'Стоимость итого\'"})]
    [View("БюдСтроиL", new string[] {
            "Номенклатура.НаимРабот as \'Номенклатура\'",
            "ЕдИзмер.Наименование as \'Единицы измерения\'",
            "Объем as \'Объем\'",
            "НачРаб as \'Начало работ\'",
            "ОкоРаб as \'Окончания работ\'",
            "Длите as \'Длительность\'",
            "БазСт as \'Базовая стоимость\'",
            "СтоимИто as \'Стоимость итого\'"})]
    public class БюдСтрои : ICSSoft.STORMNET.DataObject
    {
        
        private int fДлите;
        
        private System.DateTime fНачРаб;
        
        private float fОбъем;
        
        private float fСтоимИто;
        
        private float fБазСт;
        
        private System.DateTime fОкоРаб;
        
        private IIS.Novyjj1.Номенклатура fНоменклатура;
        
        private IIS.Novyjj1.ЕдИзмер fЕдИзмер;
        
        // *** Start programmer edit section *** (БюдСтрои CustomMembers)

        // *** End programmer edit section *** (БюдСтрои CustomMembers)

        
        /// <summary>
        /// БазСт.
        /// </summary>
        // *** Start programmer edit section *** (БюдСтрои.БазСт CustomAttributes)

        // *** End programmer edit section *** (БюдСтрои.БазСт CustomAttributes)
        public virtual float БазСт
        {
            get
            {
                // *** Start programmer edit section *** (БюдСтрои.БазСт Get start)

                // *** End programmer edit section *** (БюдСтрои.БазСт Get start)
                float result = this.fБазСт;
                // *** Start programmer edit section *** (БюдСтрои.БазСт Get end)

                // *** End programmer edit section *** (БюдСтрои.БазСт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БюдСтрои.БазСт Set start)

                // *** End programmer edit section *** (БюдСтрои.БазСт Set start)
                this.fБазСт = value;
                // *** Start programmer edit section *** (БюдСтрои.БазСт Set end)

                // *** End programmer edit section *** (БюдСтрои.БазСт Set end)
            }
        }
        
        /// <summary>
        /// Длите.
        /// </summary>
        // *** Start programmer edit section *** (БюдСтрои.Длите CustomAttributes)

        // *** End programmer edit section *** (БюдСтрои.Длите CustomAttributes)
        public virtual int Длите
        {
            get
            {
                // *** Start programmer edit section *** (БюдСтрои.Длите Get start)

                // *** End programmer edit section *** (БюдСтрои.Длите Get start)
                int result = this.fДлите;
                // *** Start programmer edit section *** (БюдСтрои.Длите Get end)

                // *** End programmer edit section *** (БюдСтрои.Длите Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БюдСтрои.Длите Set start)

                // *** End programmer edit section *** (БюдСтрои.Длите Set start)
                this.fДлите = value;
                // *** Start programmer edit section *** (БюдСтрои.Длите Set end)

                // *** End programmer edit section *** (БюдСтрои.Длите Set end)
            }
        }
        
        /// <summary>
        /// НачРаб.
        /// </summary>
        // *** Start programmer edit section *** (БюдСтрои.НачРаб CustomAttributes)

        // *** End programmer edit section *** (БюдСтрои.НачРаб CustomAttributes)
        public virtual System.DateTime НачРаб
        {
            get
            {
                // *** Start programmer edit section *** (БюдСтрои.НачРаб Get start)

                // *** End programmer edit section *** (БюдСтрои.НачРаб Get start)
                System.DateTime result = this.fНачРаб;
                // *** Start programmer edit section *** (БюдСтрои.НачРаб Get end)

                // *** End programmer edit section *** (БюдСтрои.НачРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БюдСтрои.НачРаб Set start)

                // *** End programmer edit section *** (БюдСтрои.НачРаб Set start)
                this.fНачРаб = value;
                // *** Start programmer edit section *** (БюдСтрои.НачРаб Set end)

                // *** End programmer edit section *** (БюдСтрои.НачРаб Set end)
            }
        }
        
        /// <summary>
        /// Объем.
        /// </summary>
        // *** Start programmer edit section *** (БюдСтрои.Объем CustomAttributes)

        // *** End programmer edit section *** (БюдСтрои.Объем CustomAttributes)
        public virtual float Объем
        {
            get
            {
                // *** Start programmer edit section *** (БюдСтрои.Объем Get start)

                // *** End programmer edit section *** (БюдСтрои.Объем Get start)
                float result = this.fОбъем;
                // *** Start programmer edit section *** (БюдСтрои.Объем Get end)

                // *** End programmer edit section *** (БюдСтрои.Объем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БюдСтрои.Объем Set start)

                // *** End programmer edit section *** (БюдСтрои.Объем Set start)
                this.fОбъем = value;
                // *** Start programmer edit section *** (БюдСтрои.Объем Set end)

                // *** End programmer edit section *** (БюдСтрои.Объем Set end)
            }
        }
        
        /// <summary>
        /// ОкоРаб.
        /// </summary>
        // *** Start programmer edit section *** (БюдСтрои.ОкоРаб CustomAttributes)

        // *** End programmer edit section *** (БюдСтрои.ОкоРаб CustomAttributes)
        public virtual System.DateTime ОкоРаб
        {
            get
            {
                // *** Start programmer edit section *** (БюдСтрои.ОкоРаб Get start)

                // *** End programmer edit section *** (БюдСтрои.ОкоРаб Get start)
                System.DateTime result = this.fОкоРаб;
                // *** Start programmer edit section *** (БюдСтрои.ОкоРаб Get end)

                // *** End programmer edit section *** (БюдСтрои.ОкоРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БюдСтрои.ОкоРаб Set start)

                // *** End programmer edit section *** (БюдСтрои.ОкоРаб Set start)
                this.fОкоРаб = value;
                // *** Start programmer edit section *** (БюдСтрои.ОкоРаб Set end)

                // *** End programmer edit section *** (БюдСтрои.ОкоРаб Set end)
            }
        }
        
        /// <summary>
        /// СтоимИто.
        /// </summary>
        // *** Start programmer edit section *** (БюдСтрои.СтоимИто CustomAttributes)

        // *** End programmer edit section *** (БюдСтрои.СтоимИто CustomAttributes)
        public virtual float СтоимИто
        {
            get
            {
                // *** Start programmer edit section *** (БюдСтрои.СтоимИто Get start)

                // *** End programmer edit section *** (БюдСтрои.СтоимИто Get start)
                float result = this.fСтоимИто;
                // *** Start programmer edit section *** (БюдСтрои.СтоимИто Get end)

                // *** End programmer edit section *** (БюдСтрои.СтоимИто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БюдСтрои.СтоимИто Set start)

                // *** End programmer edit section *** (БюдСтрои.СтоимИто Set start)
                this.fСтоимИто = value;
                // *** Start programmer edit section *** (БюдСтрои.СтоимИто Set end)

                // *** End programmer edit section *** (БюдСтрои.СтоимИто Set end)
            }
        }
        
        /// <summary>
        /// Бюд строи.
        /// </summary>
        // *** Start programmer edit section *** (БюдСтрои.ЕдИзмер CustomAttributes)

        // *** End programmer edit section *** (БюдСтрои.ЕдИзмер CustomAttributes)
        [PropertyStorage(new string[] {
                "ЕдИзмер"})]
        [NotNull()]
        public virtual IIS.Novyjj1.ЕдИзмер ЕдИзмер
        {
            get
            {
                // *** Start programmer edit section *** (БюдСтрои.ЕдИзмер Get start)

                // *** End programmer edit section *** (БюдСтрои.ЕдИзмер Get start)
                IIS.Novyjj1.ЕдИзмер result = this.fЕдИзмер;
                // *** Start programmer edit section *** (БюдСтрои.ЕдИзмер Get end)

                // *** End programmer edit section *** (БюдСтрои.ЕдИзмер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БюдСтрои.ЕдИзмер Set start)

                // *** End programmer edit section *** (БюдСтрои.ЕдИзмер Set start)
                this.fЕдИзмер = value;
                // *** Start programmer edit section *** (БюдСтрои.ЕдИзмер Set end)

                // *** End programmer edit section *** (БюдСтрои.ЕдИзмер Set end)
            }
        }
        
        /// <summary>
        /// Бюд строи.
        /// </summary>
        // *** Start programmer edit section *** (БюдСтрои.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (БюдСтрои.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Novyjj1.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (БюдСтрои.Номенклатура Get start)

                // *** End programmer edit section *** (БюдСтрои.Номенклатура Get start)
                IIS.Novyjj1.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (БюдСтрои.Номенклатура Get end)

                // *** End programmer edit section *** (БюдСтрои.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БюдСтрои.Номенклатура Set start)

                // *** End programmer edit section *** (БюдСтрои.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (БюдСтрои.Номенклатура Set end)

                // *** End programmer edit section *** (БюдСтрои.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БюдСтроиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БюдСтроиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БюдСтроиE", typeof(IIS.Novyjj1.БюдСтрои));
                }
            }
            
            /// <summary>
            /// "БюдСтроиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БюдСтроиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БюдСтроиL", typeof(IIS.Novyjj1.БюдСтрои));
                }
            }
        }
    }
}
