//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Док услов дог.
    /// </summary>
    // *** Start programmer edit section *** (ДокУсловДог CustomAttributes)

    // *** End programmer edit section *** (ДокУсловДог CustomAttributes)
    [AutoAltered()]
    [Caption("Документ условия договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокУсловДогE", new string[] {
            "Объем as \'Объем\'",
            "ДатаНач as \'Дата начала\'",
            "ДатаОконч as \'Дата окончания\'",
            "Длительн as \'Длительность\'"})]
    [View("ДокУсловДогL", new string[] {
            "Объем as \'Объем\'",
            "ДатаНач as \'Дата начала\'",
            "ДатаОконч as \'Дата окончания\'",
            "Длительн as \'Длительность\'"})]
    public class ДокУсловДог : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаНач;
        
        private System.DateTime fДатаОконч;
        
        private float fОбъем;
        
        private int fДлительн;
        
        // *** Start programmer edit section *** (ДокУсловДог CustomMembers)

        // *** End programmer edit section *** (ДокУсловДог CustomMembers)

        
        /// <summary>
        /// ДатаНач.
        /// </summary>
        // *** Start programmer edit section *** (ДокУсловДог.ДатаНач CustomAttributes)

        // *** End programmer edit section *** (ДокУсловДог.ДатаНач CustomAttributes)
        public virtual System.DateTime ДатаНач
        {
            get
            {
                // *** Start programmer edit section *** (ДокУсловДог.ДатаНач Get start)

                // *** End programmer edit section *** (ДокУсловДог.ДатаНач Get start)
                System.DateTime result = this.fДатаНач;
                // *** Start programmer edit section *** (ДокУсловДог.ДатаНач Get end)

                // *** End programmer edit section *** (ДокУсловДог.ДатаНач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокУсловДог.ДатаНач Set start)

                // *** End programmer edit section *** (ДокУсловДог.ДатаНач Set start)
                this.fДатаНач = value;
                // *** Start programmer edit section *** (ДокУсловДог.ДатаНач Set end)

                // *** End programmer edit section *** (ДокУсловДог.ДатаНач Set end)
            }
        }
        
        /// <summary>
        /// ДатаОконч.
        /// </summary>
        // *** Start programmer edit section *** (ДокУсловДог.ДатаОконч CustomAttributes)

        // *** End programmer edit section *** (ДокУсловДог.ДатаОконч CustomAttributes)
        public virtual System.DateTime ДатаОконч
        {
            get
            {
                // *** Start programmer edit section *** (ДокУсловДог.ДатаОконч Get start)

                // *** End programmer edit section *** (ДокУсловДог.ДатаОконч Get start)
                System.DateTime result = this.fДатаОконч;
                // *** Start programmer edit section *** (ДокУсловДог.ДатаОконч Get end)

                // *** End programmer edit section *** (ДокУсловДог.ДатаОконч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокУсловДог.ДатаОконч Set start)

                // *** End programmer edit section *** (ДокУсловДог.ДатаОконч Set start)
                this.fДатаОконч = value;
                // *** Start programmer edit section *** (ДокУсловДог.ДатаОконч Set end)

                // *** End programmer edit section *** (ДокУсловДог.ДатаОконч Set end)
            }
        }
        
        /// <summary>
        /// Длительн.
        /// </summary>
        // *** Start programmer edit section *** (ДокУсловДог.Длительн CustomAttributes)

        // *** End programmer edit section *** (ДокУсловДог.Длительн CustomAttributes)
        public virtual int Длительн
        {
            get
            {
                // *** Start programmer edit section *** (ДокУсловДог.Длительн Get start)

                // *** End programmer edit section *** (ДокУсловДог.Длительн Get start)
                int result = this.fДлительн;
                // *** Start programmer edit section *** (ДокУсловДог.Длительн Get end)

                // *** End programmer edit section *** (ДокУсловДог.Длительн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокУсловДог.Длительн Set start)

                // *** End programmer edit section *** (ДокУсловДог.Длительн Set start)
                this.fДлительн = value;
                // *** Start programmer edit section *** (ДокУсловДог.Длительн Set end)

                // *** End programmer edit section *** (ДокУсловДог.Длительн Set end)
            }
        }
        
        /// <summary>
        /// Объем.
        /// </summary>
        // *** Start programmer edit section *** (ДокУсловДог.Объем CustomAttributes)

        // *** End programmer edit section *** (ДокУсловДог.Объем CustomAttributes)
        public virtual float Объем
        {
            get
            {
                // *** Start programmer edit section *** (ДокУсловДог.Объем Get start)

                // *** End programmer edit section *** (ДокУсловДог.Объем Get start)
                float result = this.fОбъем;
                // *** Start programmer edit section *** (ДокУсловДог.Объем Get end)

                // *** End programmer edit section *** (ДокУсловДог.Объем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокУсловДог.Объем Set start)

                // *** End programmer edit section *** (ДокУсловДог.Объем Set start)
                this.fОбъем = value;
                // *** Start programmer edit section *** (ДокУсловДог.Объем Set end)

                // *** End programmer edit section *** (ДокУсловДог.Объем Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокУсловДогE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокУсловДогE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокУсловДогE", typeof(IIS.Novyjj1.ДокУсловДог));
                }
            }
            
            /// <summary>
            /// "ДокУсловДогL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокУсловДогL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокУсловДогL", typeof(IIS.Novyjj1.ДокУсловДог));
                }
            }
        }
    }
}
