//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ед измер.
    /// </summary>
    // *** Start programmer edit section *** (ЕдИзмер CustomAttributes)

    // *** End programmer edit section *** (ЕдИзмер CustomAttributes)
    [AutoAltered()]
    [Caption("Единицы измерения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЕдИзмерE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    [View("ЕдИзмерL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    public class ЕдИзмер : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (ЕдИзмер CustomMembers)

        // *** End programmer edit section *** (ЕдИзмер CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзмер.Код CustomAttributes)

        // *** End programmer edit section *** (ЕдИзмер.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ЕдИзмер.Код Get start)

                // *** End programmer edit section *** (ЕдИзмер.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ЕдИзмер.Код Get end)

                // *** End programmer edit section *** (ЕдИзмер.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЕдИзмер.Код Set start)

                // *** End programmer edit section *** (ЕдИзмер.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ЕдИзмер.Код Set end)

                // *** End programmer edit section *** (ЕдИзмер.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзмер.Наименование CustomAttributes)

        // *** End programmer edit section *** (ЕдИзмер.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ЕдИзмер.Наименование Get start)

                // *** End programmer edit section *** (ЕдИзмер.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ЕдИзмер.Наименование Get end)

                // *** End programmer edit section *** (ЕдИзмер.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЕдИзмер.Наименование Set start)

                // *** End programmer edit section *** (ЕдИзмер.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ЕдИзмер.Наименование Set end)

                // *** End programmer edit section *** (ЕдИзмер.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЕдИзмерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЕдИзмерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЕдИзмерE", typeof(IIS.Novyjj1.ЕдИзмер));
                }
            }
            
            /// <summary>
            /// "ЕдИзмерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЕдИзмерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЕдИзмерL", typeof(IIS.Novyjj1.ЕдИзмер));
                }
            }
        }
    }
}
