//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Жур уч вып раб.
    /// </summary>
    // *** Start programmer edit section *** (ЖурУчВыпРаб CustomAttributes)

    // *** End programmer edit section *** (ЖурУчВыпРаб CustomAttributes)
    [AutoAltered()]
    [Caption("Журнал учета выполнения работа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЖурУчВыпРабE", new string[] {
            "ВыпОбРаб as \'Выполнение объема работ\'",
            "ПерВыпС as \'Дата начала выполнения работ\'",
            "ПерВыпПо as \'Дата окончания выполнения работ\'",
            "Длит as \'Длительность\'",
            "СпрСотр as \'Сотрудник\'",
            "СпрСотр.ФИО as \'Сотрудник\'"})]
    [View("ЖурУчВыпРабL", new string[] {
            "ВыпОбРаб as \'Выполнение объема работ\'",
            "ПерВыпС as \'Дата начала выполнения работ\'",
            "ПерВыпПо as \'Дата окончания выполнения работ\'",
            "Длит as \'Длительность\'",
            "СпрСотр.ФИО as \'Сотрудник\'"})]
    public class ЖурУчВыпРаб : ICSSoft.STORMNET.DataObject
    {
        
        private int fДлит;
        
        private System.DateTime fПерВыпПо;
        
        private float fВыпОбРаб;
        
        private System.DateTime fПерВыпС;
        
        private IIS.Novyjj1.СпрСотр fСпрСотр;
        
        // *** Start programmer edit section *** (ЖурУчВыпРаб CustomMembers)

        // *** End programmer edit section *** (ЖурУчВыпРаб CustomMembers)

        
        /// <summary>
        /// ВыпОбРаб.
        /// </summary>
        // *** Start programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб CustomAttributes)

        // *** End programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб CustomAttributes)
        public virtual float ВыпОбРаб
        {
            get
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб Get start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб Get start)
                float result = this.fВыпОбРаб;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб Get end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб Set start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб Set start)
                this.fВыпОбРаб = value;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб Set end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ВыпОбРаб Set end)
            }
        }
        
        /// <summary>
        /// Длит.
        /// </summary>
        // *** Start programmer edit section *** (ЖурУчВыпРаб.Длит CustomAttributes)

        // *** End programmer edit section *** (ЖурУчВыпРаб.Длит CustomAttributes)
        public virtual int Длит
        {
            get
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.Длит Get start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.Длит Get start)
                int result = this.fДлит;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.Длит Get end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.Длит Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.Длит Set start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.Длит Set start)
                this.fДлит = value;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.Длит Set end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.Длит Set end)
            }
        }
        
        /// <summary>
        /// ПерВыпПо.
        /// </summary>
        // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо CustomAttributes)

        // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо CustomAttributes)
        public virtual System.DateTime ПерВыпПо
        {
            get
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо Get start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо Get start)
                System.DateTime result = this.fПерВыпПо;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо Get end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо Set start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо Set start)
                this.fПерВыпПо = value;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо Set end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпПо Set end)
            }
        }
        
        /// <summary>
        /// ПерВыпС.
        /// </summary>
        // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпС CustomAttributes)

        // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпС CustomAttributes)
        public virtual System.DateTime ПерВыпС
        {
            get
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпС Get start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпС Get start)
                System.DateTime result = this.fПерВыпС;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпС Get end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпС Set start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпС Set start)
                this.fПерВыпС = value;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.ПерВыпС Set end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.ПерВыпС Set end)
            }
        }
        
        /// <summary>
        /// Жур уч вып раб.
        /// </summary>
        // *** Start programmer edit section *** (ЖурУчВыпРаб.СпрСотр CustomAttributes)

        // *** End programmer edit section *** (ЖурУчВыпРаб.СпрСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСотр"})]
        [NotNull()]
        public virtual IIS.Novyjj1.СпрСотр СпрСотр
        {
            get
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.СпрСотр Get start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.СпрСотр Get start)
                IIS.Novyjj1.СпрСотр result = this.fСпрСотр;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.СпрСотр Get end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.СпрСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурУчВыпРаб.СпрСотр Set start)

                // *** End programmer edit section *** (ЖурУчВыпРаб.СпрСотр Set start)
                this.fСпрСотр = value;
                // *** Start programmer edit section *** (ЖурУчВыпРаб.СпрСотр Set end)

                // *** End programmer edit section *** (ЖурУчВыпРаб.СпрСотр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЖурУчВыпРабE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖурУчВыпРабE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖурУчВыпРабE", typeof(IIS.Novyjj1.ЖурУчВыпРаб));
                }
            }
            
            /// <summary>
            /// "ЖурУчВыпРабL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖурУчВыпРабL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖурУчВыпРабL", typeof(IIS.Novyjj1.ЖурУчВыпРаб));
                }
            }
        }
    }
}
