//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенклатура.
    /// </summary>
    // *** Start programmer edit section *** (Номенклатура CustomAttributes)

    // *** End programmer edit section *** (Номенклатура CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменклатураE", new string[] {
            "КодНаим as \'Код наименования\'",
            "НаимРабот as \'Номенклатура\'"})]
    [View("НоменклатураL", new string[] {
            "КодНаим as \'Код наименования\'",
            "НаимРабот as \'Номенклатура\'"})]
    public class Номенклатура : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодНаим;
        
        private string fНаимРабот;
        
        // *** Start programmer edit section *** (Номенклатура CustomMembers)

        // *** End programmer edit section *** (Номенклатура CustomMembers)

        
        /// <summary>
        /// КодНаим.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.КодНаим CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.КодНаим CustomAttributes)
        public virtual int КодНаим
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.КодНаим Get start)

                // *** End programmer edit section *** (Номенклатура.КодНаим Get start)
                int result = this.fКодНаим;
                // *** Start programmer edit section *** (Номенклатура.КодНаим Get end)

                // *** End programmer edit section *** (Номенклатура.КодНаим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.КодНаим Set start)

                // *** End programmer edit section *** (Номенклатура.КодНаим Set start)
                this.fКодНаим = value;
                // *** Start programmer edit section *** (Номенклатура.КодНаим Set end)

                // *** End programmer edit section *** (Номенклатура.КодНаим Set end)
            }
        }
        
        /// <summary>
        /// НаимРабот.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.НаимРабот CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.НаимРабот CustomAttributes)
        [StrLen(255)]
        public virtual string НаимРабот
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.НаимРабот Get start)

                // *** End programmer edit section *** (Номенклатура.НаимРабот Get start)
                string result = this.fНаимРабот;
                // *** Start programmer edit section *** (Номенклатура.НаимРабот Get end)

                // *** End programmer edit section *** (Номенклатура.НаимРабот Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.НаимРабот Set start)

                // *** End programmer edit section *** (Номенклатура.НаимРабот Set start)
                this.fНаимРабот = value;
                // *** Start programmer edit section *** (Номенклатура.НаимРабот Set end)

                // *** End programmer edit section *** (Номенклатура.НаимРабот Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменклатураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураE", typeof(IIS.Novyjj1.Номенклатура));
                }
            }
            
            /// <summary>
            /// "НоменклатураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураL", typeof(IIS.Novyjj1.Номенклатура));
                }
            }
        }
    }
}
