//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// От о рас ос мат.
    /// </summary>
    // *** Start programmer edit section *** (ОтОРасОсМат CustomAttributes)

    // *** End programmer edit section *** (ОтОРасОсМат CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет о расходах основных материалов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтОРасОсМатE", new string[] {
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.НаимРабот as \'Номенклатура\'",
            "ЕдИзмер as \'Единицы измерения\'",
            "ЕдИзмер.Наименование as \'Единицы измерения\'",
            "НормРасх as \'Норма расхода\'",
            "КолПоАкт as \'Количество по актам\'",
            "КолПоСме as \'Количество по смете\'",
            "ОбРабПоСм as \'Объем работ по смете\'",
            "ОстПоСмет as \'Остаток по смете\'",
            "СпрСотр as \'Сотрудник\'",
            "СпрСотр.ФИО as \'Сотрудник\'"})]
    [View("ОтОРасОсМатL", new string[] {
            "Номенклатура.НаимРабот as \'Номенклатура\'",
            "ЕдИзмер.Наименование as \'Единицы измерения\'",
            "НормРасх as \'Норма расхода\'",
            "КолПоАкт as \'Количество по актам\'",
            "КолПоСме as \'Количество по смете\'",
            "ОбРабПоСм as \'Объем работ по смете\'",
            "ОстПоСмет as \'Остаток по смете\'",
            "СпрСотр.ФИО as \'Сотрудник\'"})]
    public class ОтОРасОсМат : ICSSoft.STORMNET.DataObject
    {
        
        private float fКолПоАкт;
        
        private float fОбРабПоСм;
        
        private float fНормРасх;
        
        private float fОстПоСмет;
        
        private float fКолПоСме;
        
        private IIS.Novyjj1.СпрСотр fСпрСотр;
        
        private IIS.Novyjj1.Номенклатура fНоменклатура;
        
        private IIS.Novyjj1.ЕдИзмер fЕдИзмер;
        
        // *** Start programmer edit section *** (ОтОРасОсМат CustomMembers)

        // *** End programmer edit section *** (ОтОРасОсМат CustomMembers)

        
        /// <summary>
        /// КолПоАкт.
        /// </summary>
        // *** Start programmer edit section *** (ОтОРасОсМат.КолПоАкт CustomAttributes)

        // *** End programmer edit section *** (ОтОРасОсМат.КолПоАкт CustomAttributes)
        public virtual float КолПоАкт
        {
            get
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.КолПоАкт Get start)

                // *** End programmer edit section *** (ОтОРасОсМат.КолПоАкт Get start)
                float result = this.fКолПоАкт;
                // *** Start programmer edit section *** (ОтОРасОсМат.КолПоАкт Get end)

                // *** End programmer edit section *** (ОтОРасОсМат.КолПоАкт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.КолПоАкт Set start)

                // *** End programmer edit section *** (ОтОРасОсМат.КолПоАкт Set start)
                this.fКолПоАкт = value;
                // *** Start programmer edit section *** (ОтОРасОсМат.КолПоАкт Set end)

                // *** End programmer edit section *** (ОтОРасОсМат.КолПоАкт Set end)
            }
        }
        
        /// <summary>
        /// КолПоСме.
        /// </summary>
        // *** Start programmer edit section *** (ОтОРасОсМат.КолПоСме CustomAttributes)

        // *** End programmer edit section *** (ОтОРасОсМат.КолПоСме CustomAttributes)
        public virtual float КолПоСме
        {
            get
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.КолПоСме Get start)

                // *** End programmer edit section *** (ОтОРасОсМат.КолПоСме Get start)
                float result = this.fКолПоСме;
                // *** Start programmer edit section *** (ОтОРасОсМат.КолПоСме Get end)

                // *** End programmer edit section *** (ОтОРасОсМат.КолПоСме Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.КолПоСме Set start)

                // *** End programmer edit section *** (ОтОРасОсМат.КолПоСме Set start)
                this.fКолПоСме = value;
                // *** Start programmer edit section *** (ОтОРасОсМат.КолПоСме Set end)

                // *** End programmer edit section *** (ОтОРасОсМат.КолПоСме Set end)
            }
        }
        
        /// <summary>
        /// НормРасх.
        /// </summary>
        // *** Start programmer edit section *** (ОтОРасОсМат.НормРасх CustomAttributes)

        // *** End programmer edit section *** (ОтОРасОсМат.НормРасх CustomAttributes)
        public virtual float НормРасх
        {
            get
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.НормРасх Get start)

                // *** End programmer edit section *** (ОтОРасОсМат.НормРасх Get start)
                float result = this.fНормРасх;
                // *** Start programmer edit section *** (ОтОРасОсМат.НормРасх Get end)

                // *** End programmer edit section *** (ОтОРасОсМат.НормРасх Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.НормРасх Set start)

                // *** End programmer edit section *** (ОтОРасОсМат.НормРасх Set start)
                this.fНормРасх = value;
                // *** Start programmer edit section *** (ОтОРасОсМат.НормРасх Set end)

                // *** End programmer edit section *** (ОтОРасОсМат.НормРасх Set end)
            }
        }
        
        /// <summary>
        /// ОбРабПоСм.
        /// </summary>
        // *** Start programmer edit section *** (ОтОРасОсМат.ОбРабПоСм CustomAttributes)

        // *** End programmer edit section *** (ОтОРасОсМат.ОбРабПоСм CustomAttributes)
        public virtual float ОбРабПоСм
        {
            get
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.ОбРабПоСм Get start)

                // *** End programmer edit section *** (ОтОРасОсМат.ОбРабПоСм Get start)
                float result = this.fОбРабПоСм;
                // *** Start programmer edit section *** (ОтОРасОсМат.ОбРабПоСм Get end)

                // *** End programmer edit section *** (ОтОРасОсМат.ОбРабПоСм Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.ОбРабПоСм Set start)

                // *** End programmer edit section *** (ОтОРасОсМат.ОбРабПоСм Set start)
                this.fОбРабПоСм = value;
                // *** Start programmer edit section *** (ОтОРасОсМат.ОбРабПоСм Set end)

                // *** End programmer edit section *** (ОтОРасОсМат.ОбРабПоСм Set end)
            }
        }
        
        /// <summary>
        /// ОстПоСмет.
        /// </summary>
        // *** Start programmer edit section *** (ОтОРасОсМат.ОстПоСмет CustomAttributes)

        // *** End programmer edit section *** (ОтОРасОсМат.ОстПоСмет CustomAttributes)
        public virtual float ОстПоСмет
        {
            get
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.ОстПоСмет Get start)

                // *** End programmer edit section *** (ОтОРасОсМат.ОстПоСмет Get start)
                float result = this.fОстПоСмет;
                // *** Start programmer edit section *** (ОтОРасОсМат.ОстПоСмет Get end)

                // *** End programmer edit section *** (ОтОРасОсМат.ОстПоСмет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.ОстПоСмет Set start)

                // *** End programmer edit section *** (ОтОРасОсМат.ОстПоСмет Set start)
                this.fОстПоСмет = value;
                // *** Start programmer edit section *** (ОтОРасОсМат.ОстПоСмет Set end)

                // *** End programmer edit section *** (ОтОРасОсМат.ОстПоСмет Set end)
            }
        }
        
        /// <summary>
        /// От о рас ос мат.
        /// </summary>
        // *** Start programmer edit section *** (ОтОРасОсМат.ЕдИзмер CustomAttributes)

        // *** End programmer edit section *** (ОтОРасОсМат.ЕдИзмер CustomAttributes)
        [PropertyStorage(new string[] {
                "ЕдИзмер"})]
        [NotNull()]
        public virtual IIS.Novyjj1.ЕдИзмер ЕдИзмер
        {
            get
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.ЕдИзмер Get start)

                // *** End programmer edit section *** (ОтОРасОсМат.ЕдИзмер Get start)
                IIS.Novyjj1.ЕдИзмер result = this.fЕдИзмер;
                // *** Start programmer edit section *** (ОтОРасОсМат.ЕдИзмер Get end)

                // *** End programmer edit section *** (ОтОРасОсМат.ЕдИзмер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.ЕдИзмер Set start)

                // *** End programmer edit section *** (ОтОРасОсМат.ЕдИзмер Set start)
                this.fЕдИзмер = value;
                // *** Start programmer edit section *** (ОтОРасОсМат.ЕдИзмер Set end)

                // *** End programmer edit section *** (ОтОРасОсМат.ЕдИзмер Set end)
            }
        }
        
        /// <summary>
        /// От о рас ос мат.
        /// </summary>
        // *** Start programmer edit section *** (ОтОРасОсМат.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (ОтОРасОсМат.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Novyjj1.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.Номенклатура Get start)

                // *** End programmer edit section *** (ОтОРасОсМат.Номенклатура Get start)
                IIS.Novyjj1.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (ОтОРасОсМат.Номенклатура Get end)

                // *** End programmer edit section *** (ОтОРасОсМат.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.Номенклатура Set start)

                // *** End programmer edit section *** (ОтОРасОсМат.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (ОтОРасОсМат.Номенклатура Set end)

                // *** End programmer edit section *** (ОтОРасОсМат.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// От о рас ос мат.
        /// </summary>
        // *** Start programmer edit section *** (ОтОРасОсМат.СпрСотр CustomAttributes)

        // *** End programmer edit section *** (ОтОРасОсМат.СпрСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСотр"})]
        [NotNull()]
        public virtual IIS.Novyjj1.СпрСотр СпрСотр
        {
            get
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.СпрСотр Get start)

                // *** End programmer edit section *** (ОтОРасОсМат.СпрСотр Get start)
                IIS.Novyjj1.СпрСотр result = this.fСпрСотр;
                // *** Start programmer edit section *** (ОтОРасОсМат.СпрСотр Get end)

                // *** End programmer edit section *** (ОтОРасОсМат.СпрСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтОРасОсМат.СпрСотр Set start)

                // *** End programmer edit section *** (ОтОРасОсМат.СпрСотр Set start)
                this.fСпрСотр = value;
                // *** Start programmer edit section *** (ОтОРасОсМат.СпрСотр Set end)

                // *** End programmer edit section *** (ОтОРасОсМат.СпрСотр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтОРасОсМатE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтОРасОсМатE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтОРасОсМатE", typeof(IIS.Novyjj1.ОтОРасОсМат));
                }
            }
            
            /// <summary>
            /// "ОтОРасОсМатL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтОРасОсМатL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтОРасОсМатL", typeof(IIS.Novyjj1.ОтОРасОсМат));
                }
            }
        }
    }
}
