//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пл ф ан вып раб.
    /// </summary>
    // *** Start programmer edit section *** (ПлФАнВыпРаб CustomAttributes)

    // *** End programmer edit section *** (ПлФАнВыпРаб CustomAttributes)
    [AutoAltered()]
    [Caption("План фактный анализ выполнения работ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПлФАнВыпРабE", new string[] {
            "ПланОб as \'План объем\'",
            "ПланСум as \'План сумма\'",
            "РеализовОб as \'Реализовано объем\'",
            "РеализоСум as \'Реализовано сумма\'",
            "ВыпОб as \'Выполнено объем\'",
            "ВыпСум as \'Выполнено сумма\'",
            "ВсегоОб as \'Всего объем\'",
            "ВсегоСум as \'Всего сумма\'"})]
    [View("ПлФАнВыпРабL", new string[] {
            "ПланОб as \'План объем\'",
            "ПланСум as \'План сумма\'",
            "РеализовОб as \'Реализовано объем\'",
            "РеализоСум as \'Реализовано сумма\'",
            "ВыпОб as \'Выполнено объем\'",
            "ВыпСум as \'Выполнено сумма\'",
            "ВсегоОб as \'Всего объем\'",
            "ВсегоСум as \'Всего сумма\'"})]
    public class ПлФАнВыпРаб : ICSSoft.STORMNET.DataObject
    {
        
        private float fВсегоОб;
        
        private float fПланСум;
        
        private float fВсегоСум;
        
        private float fПланОб;
        
        private float fРеализовОб;
        
        private float fРеализоСум;
        
        private float fВыпОб;
        
        private float fВыпСум;
        
        // *** Start programmer edit section *** (ПлФАнВыпРаб CustomMembers)

        // *** End programmer edit section *** (ПлФАнВыпРаб CustomMembers)

        
        /// <summary>
        /// ВсегоОб.
        /// </summary>
        // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоОб CustomAttributes)

        // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоОб CustomAttributes)
        public virtual float ВсегоОб
        {
            get
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоОб Get start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоОб Get start)
                float result = this.fВсегоОб;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоОб Get end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоОб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоОб Set start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоОб Set start)
                this.fВсегоОб = value;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоОб Set end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоОб Set end)
            }
        }
        
        /// <summary>
        /// ВсегоСум.
        /// </summary>
        // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоСум CustomAttributes)

        // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоСум CustomAttributes)
        public virtual float ВсегоСум
        {
            get
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоСум Get start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоСум Get start)
                float result = this.fВсегоСум;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоСум Get end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоСум Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоСум Set start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоСум Set start)
                this.fВсегоСум = value;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВсегоСум Set end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВсегоСум Set end)
            }
        }
        
        /// <summary>
        /// ВыпОб.
        /// </summary>
        // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпОб CustomAttributes)

        // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпОб CustomAttributes)
        public virtual float ВыпОб
        {
            get
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпОб Get start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпОб Get start)
                float result = this.fВыпОб;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпОб Get end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпОб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпОб Set start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпОб Set start)
                this.fВыпОб = value;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпОб Set end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпОб Set end)
            }
        }
        
        /// <summary>
        /// ВыпСум.
        /// </summary>
        // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпСум CustomAttributes)

        // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпСум CustomAttributes)
        public virtual float ВыпСум
        {
            get
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпСум Get start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпСум Get start)
                float result = this.fВыпСум;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпСум Get end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпСум Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпСум Set start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпСум Set start)
                this.fВыпСум = value;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ВыпСум Set end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ВыпСум Set end)
            }
        }
        
        /// <summary>
        /// ПланОб.
        /// </summary>
        // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланОб CustomAttributes)

        // *** End programmer edit section *** (ПлФАнВыпРаб.ПланОб CustomAttributes)
        public virtual float ПланОб
        {
            get
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланОб Get start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ПланОб Get start)
                float result = this.fПланОб;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланОб Get end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ПланОб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланОб Set start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ПланОб Set start)
                this.fПланОб = value;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланОб Set end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ПланОб Set end)
            }
        }
        
        /// <summary>
        /// ПланСум.
        /// </summary>
        // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланСум CustomAttributes)

        // *** End programmer edit section *** (ПлФАнВыпРаб.ПланСум CustomAttributes)
        public virtual float ПланСум
        {
            get
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланСум Get start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ПланСум Get start)
                float result = this.fПланСум;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланСум Get end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ПланСум Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланСум Set start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ПланСум Set start)
                this.fПланСум = value;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.ПланСум Set end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.ПланСум Set end)
            }
        }
        
        /// <summary>
        /// РеализовОб.
        /// </summary>
        // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализовОб CustomAttributes)

        // *** End programmer edit section *** (ПлФАнВыпРаб.РеализовОб CustomAttributes)
        public virtual float РеализовОб
        {
            get
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализовОб Get start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.РеализовОб Get start)
                float result = this.fРеализовОб;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализовОб Get end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.РеализовОб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализовОб Set start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.РеализовОб Set start)
                this.fРеализовОб = value;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализовОб Set end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.РеализовОб Set end)
            }
        }
        
        /// <summary>
        /// РеализоСум.
        /// </summary>
        // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализоСум CustomAttributes)

        // *** End programmer edit section *** (ПлФАнВыпРаб.РеализоСум CustomAttributes)
        public virtual float РеализоСум
        {
            get
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализоСум Get start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.РеализоСум Get start)
                float result = this.fРеализоСум;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализоСум Get end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.РеализоСум Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализоСум Set start)

                // *** End programmer edit section *** (ПлФАнВыпРаб.РеализоСум Set start)
                this.fРеализоСум = value;
                // *** Start programmer edit section *** (ПлФАнВыпРаб.РеализоСум Set end)

                // *** End programmer edit section *** (ПлФАнВыпРаб.РеализоСум Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПлФАнВыпРабE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПлФАнВыпРабE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПлФАнВыпРабE", typeof(IIS.Novyjj1.ПлФАнВыпРаб));
                }
            }
            
            /// <summary>
            /// "ПлФАнВыпРабL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПлФАнВыпРабL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПлФАнВыпРабL", typeof(IIS.Novyjj1.ПлФАнВыпРаб));
                }
            }
        }
    }
}
