//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр сотр.
    /// </summary>
    // *** Start programmer edit section *** (СпрСотр CustomAttributes)

    // *** End programmer edit section *** (СпрСотр CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник сотрудники")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрСотрE", new string[] {
            "ФИО as \'ФИО\'",
            "IDСотр as \'ID Сотрудника\'"})]
    [View("СпрСотрL", new string[] {
            "ФИО as \'ФИО\'",
            "IDСотр as \'ID Сотрудника\'"})]
    public class СпрСотр : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fIDСотр;
        
        // *** Start programmer edit section *** (СпрСотр CustomMembers)

        // *** End programmer edit section *** (СпрСотр CustomMembers)

        
        /// <summary>
        /// IDСотр.
        /// </summary>
        // *** Start programmer edit section *** (СпрСотр.IDСотр CustomAttributes)

        // *** End programmer edit section *** (СпрСотр.IDСотр CustomAttributes)
        public virtual int IDСотр
        {
            get
            {
                // *** Start programmer edit section *** (СпрСотр.IDСотр Get start)

                // *** End programmer edit section *** (СпрСотр.IDСотр Get start)
                int result = this.fIDСотр;
                // *** Start programmer edit section *** (СпрСотр.IDСотр Get end)

                // *** End programmer edit section *** (СпрСотр.IDСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрСотр.IDСотр Set start)

                // *** End programmer edit section *** (СпрСотр.IDСотр Set start)
                this.fIDСотр = value;
                // *** Start programmer edit section *** (СпрСотр.IDСотр Set end)

                // *** End programmer edit section *** (СпрСотр.IDСотр Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (СпрСотр.ФИО CustomAttributes)

        // *** End programmer edit section *** (СпрСотр.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (СпрСотр.ФИО Get start)

                // *** End programmer edit section *** (СпрСотр.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (СпрСотр.ФИО Get end)

                // *** End programmer edit section *** (СпрСотр.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрСотр.ФИО Set start)

                // *** End programmer edit section *** (СпрСотр.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (СпрСотр.ФИО Set end)

                // *** End programmer edit section *** (СпрСотр.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрСотрE", typeof(IIS.Novyjj1.СпрСотр));
                }
            }
            
            /// <summary>
            /// "СпрСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрСотрL", typeof(IIS.Novyjj1.СпрСотр));
                }
            }
        }
    }
}
